/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    problems: Problem;
    media: Media;
    services: Service;
    customers: Customer;
    partnerships: Partnership;
    careers: Career;
    products: Product;
    faqs: Faq;
    portfolios: Portfolio;
    visitors: Visitor;
    'pricing-faqs': PricingFaq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    problems: ProblemsSelect<false> | ProblemsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    partnerships: PartnershipsSelect<false> | PartnershipsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    portfolios: PortfoliosSelect<false> | PortfoliosSelect<true>;
    visitors: VisitorsSelect<false> | VisitorsSelect<true>;
    'pricing-faqs': PricingFaqsSelect<false> | PricingFaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'about-us': AboutUs;
  };
  globalsSelect: {
    'about-us': AboutUsSelect<false> | AboutUsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problems".
 */
export interface Problem {
  id: number;
  title: string;
  description: string;
  icon: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Wajib diisi untuk SEO dan aksesibilitas (Tunanetra). Deskripsikan isi gambar.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  /**
   * Pengganti teks 'LAYANAN KAMI'. Misal: Enterprise Software, Cloud Solution, dll.
   */
  category?: string | null;
  /**
   * Teks ini akan muncul di tooltip navigasi AppBar dan Card daftar layanan.
   */
  subtitle: string;
  /**
   * Gunakan gambar berformat SVG atau PNG dengan rasio 1:1.
   */
  iconTitle: number | Media;
  dashboardBadge?: string | null;
  dashboardTitle?: string | null;
  dashboardSubtitle?: string | null;
  /**
   * Data untuk card kecil yang melayang di pojok kiri atas dan kanan bawah gambar.
   */
  floatingCards?: {
    topLeft?: {
      title?: string | null;
      subtitle?: string | null;
      dotColor?: ('green' | 'orange' | 'blue') | null;
    };
    bottomRight?: {
      title?: string | null;
      subtitle?: string | null;
      dotColor?: ('green' | 'orange' | 'blue') | null;
    };
  };
  heroBadge?: string | null;
  heroDescription?: string | null;
  heroImage?: (number | null) | Media;
  heroBtn1Text?: string | null;
  heroBtn1Link?: string | null;
  heroBtn2Text?: string | null;
  heroBtn2Link?: string | null;
  showProblem?: boolean | null;
  problem?: {
    badge?: string | null;
    title?: string | null;
    subtitle?: string | null;
    cards?:
      | {
          icon?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  showSolution?: boolean | null;
  solution?: {
    badge?: string | null;
    title?: string | null;
    list?:
      | {
          badge?: string | null;
          title?: string | null;
          description?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  showProcess?: boolean | null;
  process?: {
    badge?: string | null;
    title?: string | null;
    subtitle?: string | null;
    steps?:
      | {
          icon?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  showFramework?: boolean | null;
  framework?: {
    title?: string | null;
    subtitle?: string | null;
    logos?:
      | {
          logo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  showBenefit?: boolean | null;
  benefit?: {
    badge?: string | null;
    title?: string | null;
    subtitle?: string | null;
    cards?:
      | {
          icon?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  showPricing?: boolean | null;
  pricing?: {
    pricingHeadline?: string | null;
    pricingDescription?: string | null;
    tiers?:
      | {
          isPopular?: boolean | null;
          tierName?: string | null;
          price?: string | null;
          priceSuffix?: string | null;
          description?: string | null;
          features?:
            | {
                featureItem?: string | null;
                id?: string | null;
              }[]
            | null;
          buttonText?: string | null;
          buttonLink?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerships".
 */
export interface Partnership {
  id: number;
  name: string;
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  slug: string;
  isUrgent?: boolean | null;
  category: 'developer' | 'administrasi' | 'marketing' | 'internship' | 'freelance';
  image: number | Media;
  /**
   * Tampil di kartu list dan paragraf pembuka di halaman detail.
   */
  shortDescription: string;
  skill: string;
  experience: string;
  location: 'On-Site' | 'Hybrid' | 'Remote';
  type: 'Full-Time' | 'Part-Time' | 'Contract' | 'Internship';
  /**
   * Gunakan fitur Bullet List di sini untuk menuliskan poin-poin Jobdesk dan Requirement sesuai desain.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Daftar produk internal yang akan tampil sebagai Tab di halaman muka dan halaman Detail Produk.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * Link ke landing page eksternal produk ini (Misal: https://bithrms.com)
   */
  productUrl: string;
  slug: string;
  /**
   * Teks tombol yang mengarahkan ke URL Website Produk di atas.
   */
  ctaText?: string | null;
  /**
   * Teks ini akan muncul di tooltip navigasi AppBar dan Card daftar layanan.
   */
  subtitle: string;
  /**
   * Gunakan gambar berformat SVG atau PNG dengan rasio 1:1.
   */
  iconTitle: number | Media;
  badge?: string | null;
  headline: string;
  /**
   * Muncul di Hero section halaman muka dan halaman detail.
   */
  description: string;
  image: number | Media;
  /**
   * Ceritakan latar belakang, visi, dan solusi menyeluruh dari produk ini.
   */
  fullDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefitTitle: string;
  benefitDescription: string;
  benefits?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        icon?: (number | null) | Media;
        title: string;
        description: string;
        picture?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  useCases?:
    | {
        industry: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        galleryImage: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Sistem yang bisa dihubungkan. Misal: SAP, Android, iOS, Hardware Khusus.
   */
  integrations?:
    | {
        logo?: (number | null) | Media;
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Tampilkan logo perusahaan sebagai social proof.
   */
  clients?:
    | {
        clientLogo: number | Media;
        clientName?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola daftar FAQ berdasarkan kategori Tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  categoryName: string;
  icon?: (number | null) | Media;
  qnaList?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Daftar rekam jejak / portofolio proyek klien.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios".
 */
export interface Portfolio {
  id: number;
  clientName: string;
  /**
   * Pilih data customer dari tabel Customers jika ada.
   */
  customer?: (number | null) | Customer;
  relatedServices?: (number | Service)[] | null;
  description: string;
  achievements?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        label: string;
        theme?: ('software' | 'hardware') | null;
        id?: string | null;
      }[]
    | null;
  image: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Data leads/pengunjung yang mengisi form kontak web.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors".
 */
export interface Visitor {
  id: number;
  name: string;
  email: string;
  phone: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-faqs".
 */
export interface PricingFaq {
  id: number;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'problems';
        value: number | Problem;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'partnerships';
        value: number | Partnership;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'portfolios';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'visitors';
        value: number | Visitor;
      } | null)
    | ({
        relationTo: 'pricing-faqs';
        value: number | PricingFaq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "problems_select".
 */
export interface ProblemsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  subtitle?: T;
  iconTitle?: T;
  dashboardBadge?: T;
  dashboardTitle?: T;
  dashboardSubtitle?: T;
  floatingCards?:
    | T
    | {
        topLeft?:
          | T
          | {
              title?: T;
              subtitle?: T;
              dotColor?: T;
            };
        bottomRight?:
          | T
          | {
              title?: T;
              subtitle?: T;
              dotColor?: T;
            };
      };
  heroBadge?: T;
  heroDescription?: T;
  heroImage?: T;
  heroBtn1Text?: T;
  heroBtn1Link?: T;
  heroBtn2Text?: T;
  heroBtn2Link?: T;
  showProblem?: T;
  problem?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  showSolution?: T;
  solution?:
    | T
    | {
        badge?: T;
        title?: T;
        list?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
              image?: T;
              id?: T;
            };
      };
  showProcess?: T;
  process?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        steps?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  showFramework?: T;
  framework?:
    | T
    | {
        title?: T;
        subtitle?: T;
        logos?:
          | T
          | {
              logo?: T;
              id?: T;
            };
      };
  showBenefit?: T;
  benefit?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  showPricing?: T;
  pricing?:
    | T
    | {
        pricingHeadline?: T;
        pricingDescription?: T;
        tiers?:
          | T
          | {
              isPopular?: T;
              tierName?: T;
              price?: T;
              priceSuffix?: T;
              description?: T;
              features?:
                | T
                | {
                    featureItem?: T;
                    id?: T;
                  };
              buttonText?: T;
              buttonLink?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partnerships_select".
 */
export interface PartnershipsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isUrgent?: T;
  category?: T;
  image?: T;
  shortDescription?: T;
  skill?: T;
  experience?: T;
  location?: T;
  type?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  productUrl?: T;
  slug?: T;
  ctaText?: T;
  subtitle?: T;
  iconTitle?: T;
  badge?: T;
  headline?: T;
  description?: T;
  image?: T;
  fullDescription?: T;
  benefitTitle?: T;
  benefitDescription?: T;
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        picture?: T;
        id?: T;
      };
  useCases?:
    | T
    | {
        industry?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        galleryImage?: T;
        caption?: T;
        id?: T;
      };
  integrations?:
    | T
    | {
        logo?: T;
        name?: T;
        id?: T;
      };
  clients?:
    | T
    | {
        clientLogo?: T;
        clientName?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  categoryName?: T;
  icon?: T;
  qnaList?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios_select".
 */
export interface PortfoliosSelect<T extends boolean = true> {
  clientName?: T;
  customer?: T;
  relatedServices?: T;
  description?: T;
  achievements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        label?: T;
        theme?: T;
        id?: T;
      };
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors_select".
 */
export interface VisitorsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-faqs_select".
 */
export interface PricingFaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Pengaturan konten halaman Tentang Kami (Company Profile).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us".
 */
export interface AboutUs {
  id: number;
  heroHeadline: string;
  heroDescription: string;
  heroImage?: (number | null) | Media;
  visionText: string;
  missionList: {
    missionText: string;
    id?: string | null;
  }[];
  coreValues: {
    icon?: (number | null) | Media;
    title: string;
    description: string;
    id?: string | null;
  }[];
  milestoneHeadline?: string | null;
  milestones?:
    | {
        year: string;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  strengths: {
    title: string;
    description?: string | null;
    id?: string | null;
  }[];
  industries: {
    icon?: (number | null) | Media;
    name: string;
    id?: string | null;
  }[];
  teamHeadline: string;
  teamDescription?: string | null;
  teamMembers?:
    | {
        photo?: (number | null) | Media;
        name: string;
        position: string;
        linkedin?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaHeadline: string;
  ctaDescription?: string | null;
  ctaButtonText: string;
  ctaButtonLink: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us_select".
 */
export interface AboutUsSelect<T extends boolean = true> {
  heroHeadline?: T;
  heroDescription?: T;
  heroImage?: T;
  visionText?: T;
  missionList?:
    | T
    | {
        missionText?: T;
        id?: T;
      };
  coreValues?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  milestoneHeadline?: T;
  milestones?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  strengths?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  industries?:
    | T
    | {
        icon?: T;
        name?: T;
        id?: T;
      };
  teamHeadline?: T;
  teamDescription?: T;
  teamMembers?:
    | T
    | {
        photo?: T;
        name?: T;
        position?: T;
        linkedin?: T;
        id?: T;
      };
  ctaHeadline?: T;
  ctaDescription?: T;
  ctaButtonText?: T;
  ctaButtonLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}